version: "3.7"

services:
  helpers:
    image: helpers:local
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: helpers-container
    entrypoint: "/helpers/init.sh"
    env_file:
      - secrets/env-local
    ports:
      # src:dest (src=port on container, dest=port on host machine)
      - "7741:7740" # Port for Jupyter notwbook
      - "8889:8889" # For jupyter lab
      - "2222:22"   # Map port for openssh
    volumes:
      - type: bind
        source: ${JUPYTER_HOME_LOCAL}
        target: ${JUPYTER_HOME_IMAGE}
      - type: bind
        source: "."
        target: "/helpers"
